#!/usr/bin/env python3
"""
FastLocations — local scoring API.

  pip install -r requirements.txt
  python app.py
  open http://127.0.0.1:8000

Routes:
  GET  /         -> the intake form
  GET  /health   -> data load status (open this in a browser to confirm the API is up)
  POST /match    -> body = ProjectCriteria JSON; returns ranked results + serving EDO (?top=N, default 5)

CORS is open so the form works whether it's opened via this server, a file://, or
another local dev server (e.g. VS Code Live Server).
"""
import os, json, urllib.request
HERE=os.path.dirname(os.path.abspath(__file__))
os.environ.setdefault("FL_DATA_DIR", HERE)

from flask import Flask, request, jsonify, send_file
import scorer

app=Flask(__name__)

@app.after_request
def add_cors(resp):
    resp.headers["Access-Control-Allow-Origin"]="*"
    resp.headers["Access-Control-Allow-Headers"]="Content-Type"
    resp.headers["Access-Control-Allow-Methods"]="GET, POST, OPTIONS"
    return resp

@app.get("/")
def home():
    return send_file(os.path.join(HERE,"site_selection_intake.html"))

@app.get("/intake.js")
def intake_js():
    return send_file(os.path.join(HERE,"intake.js"), mimetype="application/javascript")

@app.get("/email-status")
def email_status():
    return {"resend_key_set": bool(os.environ.get("RESEND_API_KEY")),
            "notify_email_set": bool(os.environ.get("FL_NOTIFY_EMAIL")),
            "email_from": os.environ.get("EMAIL_FROM", "(default Resend test sender)")}

@app.get("/health")
def health():
    return {"status":"ok","counties":len(scorer.FEAT),"edos":len(scorer.MASTER),
            "states_with_incentives":len(scorer.INC)}


def send_match_email(criteria, out):
    """Email the ranked matches via Resend to the submitter + FastLocations inbox.
    Skips silently if RESEND_API_KEY is not configured."""
    key=os.environ.get("RESEND_API_KEY")
    if not key: return {"sent": False, "reason": "RESEND_API_KEY not set"}
    sb=(criteria.get("project") or {}).get("submitted_by") or {}
    submitter=(sb.get("email") or "").strip()
    notify=os.environ.get("FL_NOTIFY_EMAIL","").strip()
    to=list(dict.fromkeys([e for e in (submitter, notify) if e]))
    if not to: return {"sent": False, "reason": "no recipient email"}
    proj=(criteria.get("project") or {}).get("project_name") or "Your project"
    items=""
    for i, r in enumerate(out.get("results", []), 1):
        edo=(r.get("serving_edos") or [{}])[0]
        org=edo.get("organization","")
        items += ("<li style='margin-bottom:12px'><b>%d. %s, %s</b> &mdash; score %s"
                  "%s<br><span style='color:#555;font-size:13px'>%s</span></li>") % (
                  i, r.get("county",""), r.get("state",""), r.get("final_score",""),
                  ("<br>Route lead to: <b>%s</b>" % org) if org else "",
                  r.get("rationale",""))
    html=("<div style='font-family:Arial,sans-serif'>"
          "<h2 style='color:#1a54a0'>FastLocations matches &mdash; %s</h2>"
          "<p>Top %d locations for this project:</p><ol>%s</ol>"
          "<p style='color:#888;font-size:12px'>Generated by FastLocations.ai. "
          "Preliminary and informational only.</p></div>") % (proj, len(out.get("results",[])), items)
    payload={"from": os.environ.get("EMAIL_FROM", "FastLocations <onboarding@resend.dev>"),
             "to": to, "subject": "FastLocations matches - %s" % proj, "html": html}
    req=urllib.request.Request("https://api.resend.com/emails",
        data=json.dumps(payload).encode(),
        headers={"Authorization": "Bearer "+key, "Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return {"sent": True, "status": resp.status, "to": to}
    except Exception as e:
        return {"sent": False, "reason": str(e)[:150]}

@app.route("/match", methods=["POST","OPTIONS"])
def match():
    if request.method=="OPTIONS":
        return ("",204)
    crit=request.get_json(force=True,silent=True) or {}
    try: top=int(request.args.get("top",5))
    except ValueError: top=5
    out=scorer.run(crit,top=top)
    try: out["email"]=send_match_email(crit, out)
    except Exception as e: out["email"]={"sent": False, "reason": str(e)[:150]}
    return jsonify(out)

if __name__=="__main__":
    print("FastLocations scoring API -> http://127.0.0.1:8000  (Ctrl+C to stop)")
    app.run(host="127.0.0.1",port=8000,debug=False)
